### PR TITLE
Prevents NPE in getMismatch

### PR DESCRIPTION
**Pull request by o-orand**
fix(analyze): in getMismatch, checks version extracted from dependencies management is not null

### CODE REVIEW

**Comment by michael-o** [comment]
Just checked your PR, several issues:
1. Does this fix the symptom or the cause?
2. Cloned your demo project and cannot built due to the repos in it. Repos in a POM are deprecated. Can you convert your demo project to an IT with push it with this PR? That would greatly help.

After that I will review and get back to you.

**Comment by o-orand** [comment]
It's for the symptom, as I don't know why the version is null. So I ensure version read from dependency management is not null.
I've fix the build, and set up a travis build. Here is a build with NPE: [Travis build # 4](https://travis-ci.org/Orange-OpenSource/mdep-506-analyse-dep-mgt/builds/82920364).

Why are you saying that declaring a repo in pom is deprecated ? I can't find anything about it. I will try to convert my demo project to an IT but I'm sure I will be able to do it.

**Comment by michael-o** [comment]
The POM was designed when repo managers where not available. Now, a repo manager should handle all repos and not the POM. You will burn your public POM forever. Please read [this](http://blog.sonatype.com/2009/02/why-putting-repositories-in-your-poms-is-a-bad-idea/).

I'll wait for your project update which works with Maven Central only. Maybe we can fix the cause and not the symptom. If we can't find the reason, we should at least log the problematic spot.

**Comment by o-orand** [comment]
I've updated the project, you should be able to build it, but not yet converted to an IT

**Comment by michael-o** [comment]
I think, I will go ahead and merge your PR. Though, I'd like to ask you to merge the check as `!= null` in next if block. That would make it concise.

**Comment by michael-o** [comment]
About the IT: I think that your example can be condensed to one module project. Define the partial depMngt section, Add the dependency with a version. The goal should fail.

**Comment by o-orand** [comment]
@michael-o thanks, I'll try to condense to one module, and I'll get back to you if it's doesn't work (I don't know how to create a test with multiple modules). What is the test naming convention: a directory name starting with mdep-506-... or not ?

**Comment by michael-o** [comment]
Awesome. I will wait for your result. `MDEP-506` is fully sufficient because it refers to the ticket. That is enough.

**Comment by o-orand** [comment]
Here it is :-). I hope it'll be fine.

**Comment by michael-o** [comment]
@o-orand Does not look bad at all. I will pull, make a few tweaks and commit it. You'll be noticed.

**Comment by michael-o** [comment]
Patch applied with simplifications. Thanks for your great contribution! Please close this PR.

**Comment by o-orand** [comment]
You're welcome.

**Pull request closed without merging**
