### PR TITLE
MCOMPILER-306 Fix `compilerArgs` example usage

### PR DESCRIPTION
**Pull request by Stephan202**

### CODE REVIEW

**Comment by Stephan202** [comment]
I have rebased the branch on `trunk`. Since this is such a trivial change: maybe one of the maintainers can spend two minutes reviewing it?

**Comment by Stephan202** [comment]
Rebased again. Ping?

**Comment by michael-o** [comment]
@Stephan202 Please close, this has been merged.

**Comment by Stephan202** [comment]
To be clear, this hasn't been merged into this deprecated repository, but rather in apache/maven-compiler-plugin#9.

**Pull request closed without merging**
