### PR TITLE
[MPIR-295]: enhancements on dependency convergence report

### PR DESCRIPTION
**Pull request by wangyf2010**
Previously, dependency convergence report have below problems:
1. Only take care directive dependencies, not include transive dependencies into analyzing.
   In fact, more version conflicting cases are happening on transive dependencies.
2. Only effective for reactor build.
   For those single maven project, also need to analyze version conflicting.
3. Show all dependencies in report, even it is a good dependency.
   That would confuse users.
4. Without dependency hierachy, it's hard for users to resolve version conflicting issues.

To resolve above problems, have these enhancements:
1. include transive dependencies.
2. effective for both reactor build and single build.
3. only show version conflicting dependency & snapshot dependency in report.
4. show clear dependency hierachy for version conflicting dependency.

### CODE REVIEW

**Comment by michael-o** [comment]
Patch needs some polish:
1. Some spots are not obeying the Maven code convention
2. List traversals aren't using enhanced for loop sometimes
3. Do not include English strings into non-English bundles

**Comment by wangyf2010** [comment]
Thanks for your comments, michael-o!

Polish code by your comments. Please review it.

**Comment by michael-o** [comment]
Way better now. If nobody else will take into this. I will have a look at the weekend.

**Comment by wangyf2010** [comment]
Great, thanks Michael.

**Comment by michael-o** [comment]
One more isse, are you able to provide some real life online project where one (I) can see the improvements you made?

**Comment by wangyf2010** [comment]
please use this project.
https://github.com/wangyf2010/maven-shared/tree/project-info-testing/maven-dependency-analyzer

Steps:
1. install enhanced maven-project-info-report-plugin into local maven repo from source code.
    source code is here:
    https://github.com/wangyf2010/maven-plugins/tree/trunk/maven-project-info-reports-plugin
2. clone above target project(that's the real maven project. :) ).
3. mvn clean site in "maven-dependency-analyzer" project.
4. open "target/site/dependency-convergence.html" and check it.

Please let me know if there are any problems.

**Comment by michael-o** [comment]
Simon, I recently failed on processing on another PR, so I have to inquire with Infra first, how I can merge and close this PR cleanly.

**Comment by wangyf2010** [comment]
Got it, thanks for following up with it, Michael!
Anyway, please let me know if there are any problems.

**Comment by michael-o** [comment]
Hi Simon, I am no checking your PR. It seems like here is no Git repo for plugins at Apache. I will try to apply your patch to SVN trunk, check it and the it if looks good, will commit.

**Comment by michael-o** [comment]
Are you able to build your test project? I receive following test error:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.apache.maven.shared.utils.CaseTest
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.234 sec <<< FAILURE! - in org.apache.maven.shared.util
s.CaseTest
testTurkishI(org.apache.maven.shared.utils.CaseTest)  Time elapsed: 0.031 sec  <<< FAILURE!
org.junit.ComparisonFailure: 'iI??'.toLowerCase('en')=='ii?i' expected:<ii?i[]> but was:<ii?i[?]>
        at org.junit.Assert.assertEquals(Assert.java:115)
        at org.apache.maven.shared.utils.CaseTest.testTurkishI(CaseTest.java:85)
```

I am on Windows with JDK 7,

**Comment by michael-o** [comment]
I have retried that on FreeBSD 9, same issue:

```
Tests run: 162, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.126 sec - in org.apache.maven.shared.utils.StringUtilsTest

Results :

Failed tests:
  CaseTest.testTurkishI:85->Assert.assertEquals:115 'iIıİ'.toLowerCase('en')=='iiıi' expected:<iiıi[]> but was:<iiıi[̇]>
```

**Comment by wangyf2010** [comment]
Hi, Michael,

Sorry, reply you so late. Please refer step 3.

```
3. mvn clean site in "maven-dependency-analyzer" project.
```

could you just run "mvn clean site" for testing purpose?
I don't think it's needed to run "test".

Regards
Simon

**Comment by michael-o** [comment]
Simon,

I was finally able to make everything run. Here are my comments:
1. You do not show the positive cases anymore but you still leave the legend for it. Why?
2. "Number of version Conflicting artifacts" should read "Number of version-conflicting artifacts"
3. "Ready for Release (100% Convergence and no SNAPSHOTS):" should read "Ready for release (100% convergence and no SNAPSHOTS):"
4. I do not think that an alphabetic numbering makes sense now because due to the trees we have aa. or ba. Too much, I would rather switch to numeric.
5. The links to the tree artfacts seem to be arbitrary and not linked to the problematic artifact. Broken?
6. Analysis for org.apache.maven:maven-settings:2.0.4 lists org.apache.maven.plugin-testing:maven-plugin-testing-tools:1.2 27 times. Bug?

**Comment by wangyf2010** [comment]
Hi, Michael,

Thanks for your comments!

I updated commit to fix below problems that you mentioned:
1. About legend, yes, you're right, I think needn't positive legend any more.
2. Using "Number of version-conflicting artifacts".
3. Using "Ready for release (100% convergence and no SNAPSHOTS):"
4. Agree, using numeric.
5. links to the tree artifacts: Those links are project's site url instead of artifact site url, that project contains current conflicting artifact. By that link, developer know which project's pom contains problematic artifacts, and they can add "exclusions" there. So needn't change code here.
6. That isn't bug, if you hover your mouse on those links, you can see, they're belonged to different sub projects. Per 5's comments, you can see that's useful for developers.
In order to show up contained project clearly, added update to show up project info in report also.

**Comment by michael-o** [comment]
OK, I let me recheck your changes and give a response quickly.

**Comment by michael-o** [comment]
Checked and I am confused by the output I see. When I run `mvn clean site` from the parent, the convergence of `m-dep-analyzer` contains 27 submodules, when I do from the `m-dep-analyzer` itself, then there is only one. This must be an error because `m-dep-analyzer` cannot have a reactor dep convergence.

**Comment by wangyf2010** [comment]
Hi, Michael,

That's expected behavior I think.
Previously, this report is trying to analyze "reactor" build and detect version-conflicting for those sub module projects.
So for one maven session, if it includes multiple sub module projects, then will analyze all of them.

For your case, run "mvn clean site" from parent, that maven session contains multiple sub modules, so the scope would be all of these modules.
Run "mvn clean site" from "m-dep-analyzer" itself, its maven session only contains one project.
so the scope is itself.

I'm thinking whether let it analyze current project only.
Then no matter you run "mvn clean site" from parent or sub project, its scope would be "itself".
If user want to analyze multiple modules project, they need to define maven-project-info-report-plugin in parent pom.
But it would violate backward-compatibility of course.

Any comments?

Regards
Simon

**Comment by michael-o** [comment]
> That's expected behavior I think.
> Previously, this report is trying to analyze "reactor" build and detect version-conflicting for those sub module projects.
> So for one maven session, if it includes multiple sub module projects, then will analyze all of them.
> 
> For your case, run "mvn clean site" from parent, that maven session contains multiple sub modules, so the scope would be all of these modules.
> Run "mvn clean site" from "m-dep-analyzer" itself, its maven session only contains one project.
> so the scope is itself.

I see the exact opposite of your description. That is the point I am trying to make. I makes perfectly sense to have a subtree validated if there is such, i.e. > 1 modules but not if there is no reactor and one has only a simple JAR project.

> I'm thinking whether let it analyze current project only.
> Then no matter you run "mvn clean site" from parent or sub project, its scope would be "itself".
> If user want to analyze multiple modules project, they need to define maven-project-info-report-plugin in parent pom.
> But it would violate backward-compatibility of course.
> 
> Any comments?

I cannot even create the report for the module only with version 2.7. In my understanding by reading the docs of the goal, it works for reactors only. So, it does not even make sense to run this on a single module.

What we can do, is when this aggregator is run from a single module, a warning can be issued and the run skipped. Otherwise the rest remains as-is.

I would continue to analyze your PR from the top parent.

**Comment by wangyf2010** [comment]
Thanks for your comments, Michael.
Please refer my inline comments below.

> I see the exact opposite of your description. That is the point I am trying to make. I makes perfectly sense to have a subtree validated if there is such, i.e. > 1 modules but not if there is no reactor and one has only a simple JAR project.

Reactor build is an important case need to be covered. Previously, it only analyze directive dependencies, so needn't care about single project case.

But this PR is trying to analyze transitive dependencies too. That's also important to analyze single project case too.

Think about one case, one web project, this project shouldn't allow transitive dependencies version-conflicting at all, because all dependencies would be put into WEB-INF/lib, it's flattern.
For that case, if this report isn't effective for single project, then can't help on this case for sure.

> I cannot even create the report for the module only with version 2.7. In my understanding by reading the docs of the goal, it works for reactors only. So, it does not even make sense to run this on a single module.
> 
> What we can do, is when this aggregator is run from a single module, a warning can be issued and the run skipped. Otherwise the rest remains as-is.

I know 2.7 is trying to detect version-conflicting for sub tree's directive dependencies.
But fact is, that isn't strong enough for reality case. Most of version-conflicting cases happens in transitive dependencies. Even for single project, its transitive dependencies also contains version-conflicting. Especially for war project. 

So I'd prefer to make it effective both multiple module case and single module case.

**Comment by michael-o** [comment]
Simon, agreed. I have reran the entire thing from parent/reactor and from module and results differ. Both look good. Here are remarks:

General:
1. Can the dependency tree look as the output from `mvn dependency:tree`? The resemblance supports uniformity.
2. Why is the entire tree linked? The artifact in question/root cause is the root of the tree and not the transitive dependencies. Am I wrong?
3. Emphesize (HTML tag) the conflicting tree node, in a big tree that is going to be a huge help.

Module only:
1. I think the link on the tree is absolutely useless because you link the main site of the module itself. Where is the benefit? It causes confusion here.
2. "Number of sub-projects:.." is redudant in this case because it is always 1
3. "Dependencies used in sub-projects" should read "Dependencies used in this project"

Parent/reactor:
0. I'd rather replace the term "sub-project" with "module"
1. Breadcrumb and header title should say "Reactor Dependency Convergence", it makes crystal clear what the report is about
2. "project - " would be redundant due to 0

**Comment by wangyf2010** [comment]
Thanks for your valuable suggestions! Michael!
Please refer my inline comments.

> 1. Can the dependency tree look as the output from mvn dependency:tree? The resemblance supports uniformity.

You mean show up all information in one big tree, just like dependency tree?
If do that, users have to pick up conflicting node one by one, that isn't easy to resolve conflicting cases. And instead, we only need to list conflicting node related dependencies only.
That's clearer.

> 1. Why is the entire tree linked? The artifact in question/root cause is the root of the tree and not the transitive dependencies. Am I wrong?

You're right, fixed it in latest code.

> 1. Emphesize (HTML tag) the conflicting tree node, in a big tree that is going to be a huge help.

Since, needn't show the big conflicting tree, I think needn't highlight conflicting node too.
After all, root node of conflicting tree is the important point to resolve conflicting.

> Module only:
> 1. I think the link on the tree is absolutely useless because you link the main site of the module itself. Where is the benefit? It causes confusion here.
> 2. "Number of sub-projects:.." is redudant in this case because it is always 1
> 3. "Dependencies used in sub-projects" should read "Dependencies used in this project"
> Parent/reactor:
> 0. I'd rather replace the term "sub-project" with "module"
> 1. Breadcrumb and header title should say "Reactor Dependency Convergence", it makes crystal clear what the report is about
> 2. "project - " would be redundant due to 0

Great comments, fixed it in latest code.

**Comment by michael-o** [comment]
> > 1. Can the dependency tree look as the output from mvn dependency:tree? The resemblance supports uniformity.
> 
> You mean show up all information in one big tree, just like dependency tree?
> If do that, users have to pick up conflicting node one by one, that isn't easy to resolve conflicting cases. And instead, we only need to list conflicting node related dependencies only.
> That's clearer.

Sorry, I was probably not clear enough. I did not mean to expand the entire tree but referred only to the visual layout. Of course, you would present the conflicting tree only.

The rest looks very good but one issue left:

In reactor mode there are zillions of conflicts and if you take a look at `org.codehaus.plexus:plexus-utils`, version 1.1, nodes 187 to 189 are the same. This issue repeats through the entire report. A bug?

**Comment by wangyf2010** [comment]
hi, Michael,

do you mean below section?

> org.apache.maven:maven-archiver:2.6-SNAPSHOT
>     +-org.apache.maven:maven-project:2.0.5
>         +-org.apache.maven:maven-artifact-manager:2.0.5
>             +-org.apache.maven:maven-repository-metadata:2.0.5
>                 -org.codehaus.plexus:plexus-utils:1.1
> 
> org.apache.maven:maven-archiver:2.6-SNAPSHOT
>     +-org.apache.maven:maven-project:2.0.5
>         +-org.apache.maven:maven-artifact-manager:2.0.5
>             -org.codehaus.plexus:plexus-utils:1.1
> 
> org.apache.maven:maven-archiver:2.6-SNAPSHOT
>     +-org.apache.maven:maven-project:2.0.5
>         -org.codehaus.plexus:plexus-utils:1.1
> </code>

As you can see, conflicting node is involved by different nodes.
That isn't a bug I think.
It shows transitive dependencies version-conflicting issues precisely.

If above section not the one you looked, could you paste your sample?

Regards
Simon

**Comment by michael-o** [comment]
This is how it looks like here:

**Comment by wangyf2010** [comment]
yes, as you can see, 

187: maven-project involved conflicting node.
188: maven-model involved conflicting node.
189: maven-artifact involved conflicting node.

That's different.

And all these dependency trees' leaf should be "plexus-utils".
If hide "plexus-utils", might confuse users.

**Comment by michael-o** [comment]
Stupid me, sorry. I have simply overlooked that due to the mass of information. But can't this be collapsed into one tree and three level one leafs?

**Comment by wangyf2010** [comment]
Agree. Might be clearer.
But if merge those separate trees into one tree, also might bring mass info for users.
Users also need to take care of them separately.

Took a look at code, not so easy to do it.
Prefer not do it.

**Comment by michael-o** [comment]
Yes, they need to but right now, you already have hundreds of trees in that page. Do you think that they will have a good overview already? I don't think so. All we can do is to pack information.

**Comment by wangyf2010** [comment]
make sense. I'm thinking to pack information per project.

that means for one conflicting node:
might have 4 sub tree belong to 4 projects.
let project node to be root node.

**Comment by michael-o** [comment]
Yes, why not. Information would be concise and non-repeated. Do you want to change the code or is this your final change?

**Comment by wangyf2010** [comment]
updated pull request, have below changes:
1. fix one bug, to detect conflicting node correctly.
2. use dependency tree likely expression to show sub tree.
3. remove project url, it's useless, since developers will resolve conflicting by focus pom files.
4. show dependency tree per project. Results would be clearer.

**Comment by michael-o** [comment]
Hi Simon,

looks exteremly good now. I will generate the patch and apply to the Subversion repo at the weekend. Thank you very much for the great work. Keep doing. I'd be pleased to process more PRs from you.

**Comment by wangyf2010** [comment]
Thanks for your great suggestions too.

Another PR is here: https://github.com/apache/maven-enforcer/pull/13
I think Karl is working on it, but haven't get status for it about 1 week.
If you could help on it, that would be perfect.

Also I'm trying to work on maven-dependency-analyzer & maven-dependency-plugin to improve it.
Will update in dev mail list.

Glad to work with you Michael!

**Comment by michael-o** [comment]
I am evaluating the patch, running ITs and need to adapt a few things. Will then upload a patch, if that is fine, it is going to be committed.

**Comment by michael-o** [comment]
Done, [here](http://pastebin.com/69LtbJDq) is the patch, check and I will commit.

**Comment by wangyf2010** [comment]
looks good, thanks Michael!

**Comment by michael-o** [comment]
Committed with http://svn.apache.org/r1601206.

**Comment by michael-o** [comment]
Are you able to selfclose your PR?

**Comment by wangyf2010** [comment]
code is committed with http://svn.apache.org/r1601206.
close this pull request.

**Pull request closed without merging**
