### PR TITLE
Update the example of setting maven-compiler source/target to use the latest released Java version (1.8)

### PR DESCRIPTION
**Pull request by cdman**

### CODE REVIEW

**Comment by Tibor17** [comment]
I would say `-source 1.4 or higher` and keep the assertions in the text.
Is the assertions removed in 1.8?

**Comment by mfriedenhagen** [comment]
@tibor17, while assertions are still only available in > 1.4,, the old example makes Maven look very old fashioned or even outdated, lambdas are fresh and new (at least for Java), so I would like to get the PR into Maven.

**Comment by Tibor17** [comment]
@mfriedenhagen It does not matter that it looks old fashioned. The doc talks about assertions.
So it depends what kind of message you want to spread out to the world:
- usage of -source regardless of assertions or lambda
- lambda only without message of -source -target
- assertions only without message of -source -target

We can remove the words `assertions` and `lambda` and use -source 1.8. That's maybe what was initially intended to configure the compiler. The side effect that assertions are available since 1.4, or lambda 1.8 is secondary and every dev can find compiler spec of javac. That's maybe even better to remove the words like `assertions` due to Eclipse compiler may be different. I am waiting for Eclipse JDT instead of javac but that's outstanding thema.

**Comment by cdman** [comment]
What do people think about the following wording:

"For example, if you want to use the Java 8 language features (<<<-source 1.8>>>) and also want the compiled classes to be compatible with JVM 1.8 (<<<-target 1.8>>>), you can then put:"

?

**Comment by Tibor17** [comment]
+1

On Fri, Nov 20, 2015 at 12:41 PM, Attila-Mihaly Balazs <
notifications@github.com> wrote:

> What do people think about the following wording:
> 
> "For example, if you want to use the Java 8 language features (<<<-source
> 1.8>>>) and also want the compiled classes to be compatible with JVM 1.8
> (<<<-target 1.8>>>), you can then put:"
> 
> ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/apache/maven-plugins/pull/69#issuecomment-158370607.

## 

Cheers
Tibor

**Comment by mfriedenhagen** [comment]
Maybe we should give a hint to toolchains as well here? Newer Maven versions need 1.7 to run so it is always a bit odd, that source and target still default to 1.5. Anybody in need for compiling for old JVMs would probably be better off with tool chains.

**Comment by Tibor17** [comment]
@mfriedenhagen Maven core and plugins have different requirements regarding 1.7/1.5.
We may add toolchain link, but I would prefer mentioning animal-sniffer plugin.

**Comment by cdman** [comment]
@mfriedenhagen @Tibor17 - agreed that for more complex use-cases the toolchain plugin should be used. However I have little experience with it (only used it briefly) so I would limit my PR to only changing the verbiage of source / target and someone with more experience can follow up with a change that describes toolchain.

**Comment by Tibor17** [comment]
@mfriedenhagen https://github.com/mfriedenhagen do you agree to push you
proposal only for now?

On Sat, Nov 21, 2015 at 5:28 PM, Attila-Mihaly Balazs <
notifications@github.com> wrote:

> @mfriedenhagen https://github.com/mfriedenhagen @Tibor17
> https://github.com/Tibor17 - agreed that for more complex use-cases the
> toolchain plugin should be used. However I have little experience with it
> (only used it briefly) so I would limit my PR to only changing the verbiage
> of source / target and someone with more experience can follow up with a
> change that describes toolchain.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/apache/maven-plugins/pull/69#issuecomment-158660340.

## 

Cheers
Tibor

**Comment by mfriedenhagen** [comment]
I would go with @cdman 's suggestion for now. We may include a hint for toolchains in another PR.

**Comment by cdman** [comment]
There seems to be consensus here that this patch should be merged, correct?

If so, I have a n00b question: how do I proceed from here? Is there some CLA I need to sign? (sorry, this is the first time I contribute to an Apache project).

**Comment by cdman** [comment]
Ping @mfriedenhagen @Tibor17 

Happy new year!

Just making sure that this doesn't get lost between all of the other changes: how do I proceed from here? Is there some CLA I need to sign? (sorry, this is the first time I contribute to an Apache project).

**Comment by Tunaki** [comment]
You don't need to sign a CLA, I just applied the PR in [r1765195](http://svn.apache.org/viewvc?view=revision&revision=1765195). Thanks for the contribution!

**Comment by cdman** [comment]
Thank you!

**Pull request closed without merging**
