### PR TITLE
[MSHADE-182] Service file should be relocated.

### PR DESCRIPTION
**Pull request by KostyaSha**
Fixes issue when service file content is relocated, but file itself didn't.
Patch content provided by some person in jira ticket.

https://issues.apache.org/jira/browse/MSHADE-182

### CODE REVIEW

**Comment by KostyaSha** [comment]
cc @aheritier @abayer @stephenc

**Comment by KostyaSha** [comment]
cc @krosenvold

**Comment by marcuslinke** [comment]
+1

**Comment by KostyaSha** [comment]
@Tibor17 never comment to commits, please comment on `changed tab` either comment could be lost with rebase, etc.

**Comment by KostyaSha** [comment]
@Tibor17 how do you run build?
`mvn clean install` : 

```
[INFO] --- maven-plugin-plugin:3.4:addPluginArtifactMetadata (default-addPluginArtifactMetadata) @ maven-shade-plugin ---
[INFO]
[INFO] --- maven-checkstyle-plugin:2.15:check (checkstyle-check) @ maven-shade-plugin ---
[INFO] There are 2 errors reported by Checkstyle 6.1.1 with config/maven_checks.xml ruleset.
[INFO] Ignored 2 errors, 0 violation remaining.
[INFO]
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ maven-shade-plugin ---
[INFO] Installing /Users/integer/src/github/maven-plugins/maven-shade-plugin/target/maven-shade-plugin-3.0-SNAPSHOT.jar to /Users/integer/.m2/repository/org/apache/maven/plugins/maven-shade-plugin/3.0-SNAPSHOT/maven-shade-plugin-3.0-SNAPSHOT.jar
[INFO] Installing /Users/integer/src/github/maven-plugins/maven-shade-plugin/pom.xml to /Users/integer/.m2/repository/org/apache/maven/plugins/maven-shade-plugin/3.0-SNAPSHOT/maven-shade-plugin-3.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

All other errors failed the build before. Do you have some specific profiles?

**Comment by KostyaSha** [comment]
Ok, will try in-line variable.

**Comment by KostyaSha** [comment]
M.. no i can't...

**Comment by KostyaSha** [comment]
This `for` is the same as in method before that has no any checkstyle exclusions.

**Comment by KostyaSha** [comment]
@Tibor17 could you try yourself? :)

**Comment by Tibor17** [comment]
This is the command I always verify before cutting the release version. See the site generated and test results of unit tests and integration tests.
`mvn verify -P run-its`
`mvn site -P reporting`
JDK 1.6, Maven 3.0.5.

**Comment by KostyaSha** [comment]
Unfortunately i have no java 1.6. `mvn verify -P run-its` produced success build.
 `mvn site -P reporting` fails with java 1.8 because of ancient plugins in deps (afair requires maven site update + one more plugin).

**Comment by Tibor17** [comment]
If you make any updates in documentation, means src/site/, then you should check that with 
`mvn site`; Otherwise let's suppose that everything was just fine before.

**Comment by KostyaSha** [comment]
1.8 based build also enforces javadoc linting, i can't run mvn site, because this plugin has too ancient deps. 

```
[INFO] Generating "FindBugs" report             --- findbugs-maven-plugin:2.5.5:findbugs
[INFO] Locale is en
[INFO] Fork Value is true
     [java] The following errors occurred during analysis:
     [java]   Unable to get XClass for java/lang/StringBuilder
     [java]     java.lang.ArrayIndexOutOfBoundsException: 5747
     [java]       At org.objectweb.asm.ClassReader.readClass(Unknown Source)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:110)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:587)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:76)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:268)
     [java]       At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:652)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addInheritanceEdge(Subtypes2.java:1260)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addSupertypeEdges(Subtypes2.java:1233)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addClassAndGetClassVertex(Subtypes2.java:275)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addClass(Subtypes2.java:244)
     [java]       At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:941)
     [java]       At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:997)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:225)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:393)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1317)
     [java]   Unable to get XClass for java/util/regex/Pattern
     [java]     java.lang.ArrayIndexOutOfBoundsException: 10247
     [java]       At org.objectweb.asm.ClassReader.readUTF8(Unknown Source)
     [java]       At org.objectweb.asm.ClassReader.readClass(Unknown Source)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:110)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:587)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:76)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:268)
     [java]       At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:652)
     [java]       At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:932)
     [java]       At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:997)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:225)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:393)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1317)
     [java]   Unable to get XClass for java/lang/String
     [java]     java.lang.ArrayIndexOutOfBoundsException: 5747
     [java]       At org.objectweb.asm.ClassReader.readClass(Unknown Source)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:110)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:587)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:76)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:268)
     [java]       At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:652)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addInheritanceEdge(Subtypes2.java:1260)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addSupertypeEdges(Subtypes2.java:1233)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addClassAndGetClassVertex(Subtypes2.java:275)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addClass(Subtypes2.java:244)
     [java]       At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:941)
     [java]       At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:997)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:225)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:393)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1317)
     [java]   Unable to get XClass for java/util/Map$Entry
     [java]     java.lang.ArrayIndexOutOfBoundsException: 5735
     [java]       At org.objectweb.asm.ClassReader.readClass(Unknown Source)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:110)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:587)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:76)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:268)
     [java]       At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:652)
     [java]       At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:932)
     [java]       At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:997)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:225)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:393)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1317)
     [java]   Unable to get XClass for java/lang/CharSequence
     [java]     java.lang.ArrayIndexOutOfBoundsException: 5747
     [java]       At org.objectweb.asm.ClassReader.readClass(Unknown Source)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:110)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:587)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:76)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:268)
     [java]       At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:652)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addInheritanceEdge(Subtypes2.java:1260)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addSupertypeEdges(Subtypes2.java:1233)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addClassAndGetClassVertex(Subtypes2.java:275)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addClass(Subtypes2.java:244)
     [java]       At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:941)
     [java]       At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:997)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:225)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:393)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1317)
     [java]   Unable to get XClass for java/lang/Class
     [java]     java.lang.ArrayIndexOutOfBoundsException: 207
     [java]       At org.objectweb.asm.ClassReader.a(Unknown Source)
     [java]       At org.objectweb.asm.ClassReader.readUTF8(Unknown Source)
     [java]       At org.objectweb.asm.ClassReader.readClass(Unknown Source)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:110)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:587)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:76)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:268)
     [java]       At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:652)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addInheritanceEdge(Subtypes2.java:1260)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addSupertypeEdges(Subtypes2.java:1233)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addClassAndGetClassVertex(Subtypes2.java:275)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addClass(Subtypes2.java:244)
     [java]       At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:941)
     [java]       At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:997)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:225)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:393)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1317)
     [java]   Unable to get XClass for java/util/Arrays
     [java]     java.lang.ArrayIndexOutOfBoundsException: 40705
     [java]       At org.objectweb.asm.ClassReader.readClass(Unknown Source)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:110)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:587)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:76)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:268)
     [java]       At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:652)
     [java]       At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:932)
     [java]       At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:997)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:225)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:393)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1317)
     [java]   Unable to get XClass for java/lang/StringBuffer
     [java]     java.lang.ArrayIndexOutOfBoundsException: 5747
     [java]       At org.objectweb.asm.ClassReader.readClass(Unknown Source)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:110)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:587)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:76)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:268)
     [java]       At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:652)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addInheritanceEdge(Subtypes2.java:1260)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addSupertypeEdges(Subtypes2.java:1233)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addClassAndGetClassVertex(Subtypes2.java:275)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addClass(Subtypes2.java:244)
     [java]       At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:941)
     [java]       At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:997)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:225)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:393)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1317)
     [java]   Couldn't get class info for java/util/regex/Pattern
     [java]     java.lang.ArrayIndexOutOfBoundsException: 10247
     [java]       At org.objectweb.asm.ClassReader.readUTF8(Unknown Source)
     [java]       At org.objectweb.asm.ClassReader.readClass(Unknown Source)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:110)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:587)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:76)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:268)
     [java]       At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:652)
     [java]       At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:932)
     [java]       At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:997)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:225)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:393)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1317)
     [java]   Couldn't get class info for java/util/Map$Entry
     [java]     java.lang.ArrayIndexOutOfBoundsException: 5735
     [java]       At org.objectweb.asm.ClassReader.readClass(Unknown Source)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:110)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:587)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:76)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:268)
     [java]       At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:652)
     [java]       At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:932)
     [java]       At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:997)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:225)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:393)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1317)
     [java]   Couldn't get class info for java/lang/CharSequence
     [java]     java.lang.ArrayIndexOutOfBoundsException: 5747
     [java]       At org.objectweb.asm.ClassReader.readClass(Unknown Source)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:110)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:587)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:76)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:268)
     [java]       At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:652)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addInheritanceEdge(Subtypes2.java:1260)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addSupertypeEdges(Subtypes2.java:1233)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addClassAndGetClassVertex(Subtypes2.java:275)
     [java]       At edu.umd.cs.findbugs.ba.ch.Subtypes2.addClass(Subtypes2.java:244)
     [java]       At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:941)
     [java]       At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:997)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:225)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:393)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1317)
     [java]   Couldn't get class info for java/util/Arrays
     [java]     java.lang.ArrayIndexOutOfBoundsException: 40705
     [java]       At org.objectweb.asm.ClassReader.readClass(Unknown Source)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
     [java]       At org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:110)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:587)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:76)
     [java]       At edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]       At edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:268)
     [java]       At edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:652)
     [java]       At edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:932)
     [java]       At edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:997)
     [java]       At edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:225)
     [java]       At edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:393)
     [java]       At edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1317)
     [java] Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 40705
     [java]     at org.objectweb.asm.ClassReader.readClass(Unknown Source)
     [java]     at org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]     at edu.umd.cs.findbugs.asm.FBClassReader.accept(FBClassReader.java:44)
     [java]     at org.objectweb.asm.ClassReader.accept(Unknown Source)
     [java]     at edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:110)
     [java]     at edu.umd.cs.findbugs.classfile.engine.ClassParserUsingASM.parse(ClassParserUsingASM.java:587)
     [java]     at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:76)
     [java]     at edu.umd.cs.findbugs.classfile.engine.ClassInfoAnalysisEngine.analyze(ClassInfoAnalysisEngine.java:38)
     [java]     at edu.umd.cs.findbugs.classfile.impl.AnalysisCache.getClassAnalysis(AnalysisCache.java:268)
     [java]     at edu.umd.cs.findbugs.ba.XFactory.getXClass(XFactory.java:652)
     [java]     at edu.umd.cs.findbugs.ba.AnalysisContext.setAppClassList(AnalysisContext.java:932)
     [java]     at edu.umd.cs.findbugs.FindBugs2.setAppClassList(FindBugs2.java:997)
     [java]     at edu.umd.cs.findbugs.FindBugs2.execute(FindBugs2.java:225)
     [java]     at edu.umd.cs.findbugs.FindBugs.runMain(FindBugs.java:393)
     [java]     at edu.umd.cs.findbugs.FindBugs2.main(FindBugs2.java:1317)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:43 min
```

**Comment by KostyaSha** [comment]
java 1.7 works, i built site, opened index.html, navigate to checkstyle, it has 5 warnings for `ServicesResourceTransformer` all not related to changed code. 2 errors at all from different classes (= exists before). All other verifications also has no new errors.

**Comment by KostyaSha** [comment]
on java 1.6

```
[INFO] --- maven-invoker-plugin:2.0.0:verify (integration-test) @ maven-shade-plugin ---
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 48, Failed: 1, Errors: 0, Skipped: 1
[INFO] -------------------------------------------------
[ERROR] The following builds failed:
[ERROR] *  MSHADE-185/pom.xml
```

```
// Check that the dependency-reduced pom does not have expand properties in 
// dependencies. They should be left untouched.
assert project.dependencies.dependency[0].systemPath == '${java.home}/../lib/tools.jar'
```

Because it unavailable on mac os.

**Comment by KostyaSha** [comment]
on 1.6 for `mvn site` i have no checkstyle blockers.

**Comment by Tibor17** [comment]
ok, mvn site is working. You should wait for developers who are actively
working on this plugin.
If you did not get any feedback yet, you can ask them on IRC chat
irc.freenode.net @channel: maven.
If I did, I would have to skip the maintenance of Surefire and dig into
this which is not that fast.

On Thu, Jan 14, 2016 at 8:37 PM, Kanstantsin Shautsou <
notifications@github.com> wrote:

> on 1.6 for mvn site i have no checkstyle blockers.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/apache/maven-plugins/pull/79#issuecomment-171754880.

## 

Cheers
Tibor

**Comment by aheritier** [comment]
Fixed in SVN r1728966

**Comment by KostyaSha** [comment]
@aheritier cool, thanks! should i close PR?

**Comment by slaskawi** [comment]
Hey @aheritier @KostyaSha! Could you please tell me in which release this PR will be available?

**Comment by KostyaSha** [comment]
I released my own fork and using it. I have no idea what is happening in slowpoke upstream. Maybe maven not alive. Also planning move to gradle.

**Comment by aheritier** [comment]
bouhhhh :( cc @rfscholte @hboutemy

**Comment by slaskawi** [comment]
@aheritier @rfscholte @hboutemy Any news?

**Comment by KostyaSha** [comment]
@slaskawi you can use my bintray version if you want https://github.com/KostyaSha/yet-another-docker-plugin/blob/master/yet-another-docker-java/pom.xml#L23 (plus repo)

**Comment by slaskawi** [comment]
@KostyaSha Thanks a lot for the offer but I applied a work around in Infinispan repository some time ago. I would like to remove it and implement it "properly" :) But again - thanks a lot!

**Pull request closed without merging**
