### PR TITLE
MRRESOURCES-94 Lazily provide projects* velocity properties

### PR DESCRIPTION
**Pull request by famod**
Alternative approach to #123 as [suggested](https://github.com/apache/maven-plugins/pull/123#issuecomment-315438386) by @rfscholte.

### CODE REVIEW

**Comment by famod** [comment]
I tried a few things to get a project dependency into the unittest but after some time I gave up.
So for now I just extended an existing test method to trigger the replacement of `${projects}` and `${projectsSortedByOrganization}` with empty values (due to the minimal stubbed unittest setup).

**Comment by famod** [comment]
@rfscholte can you review/merge this please?

**Comment by hboutemy** [comment]
great PR: merged, thank you

**Comment by famod** [comment]
@hboutemy thanks for merging!

**Pull request closed without merging**
