### PR TITLE
MECLIPSE-738: Fix constructing a LinkedResource with a locationURI

### PR DESCRIPTION
**Pull request by josephw**
Allow that either, but not both, and not neither, of the location
properties could be set. Include tests, and upgrade JUnit to allow
use of annotations.

### CODE REVIEW

**Comment by agudian** [comment]
Thanks @josephw, I'll merge it within the next couple of days or so... :wink:

**Comment by josephw** [comment]
Thanks @agudian; I'll close this PR once it's merged into the Subversion repo.

**Comment by josephw** [comment]
@agudian ping.

**Comment by agudian** [comment]
I hear you and didn't forget you. On the weekend, I tried to get the ITs running (before applying your patch), but some of them just won't work in windows... Need to fiddle around with it some more.

**Comment by agudian** [comment]
@josephw , I've applied your patch (all but the junit version update, I changed that already for some other reasons :smile:).

Thanks again for the patch, and sorry for all the delay. I have some other stuff on my todo-list before I do the 2.10 release. But it'll come...

**Comment by josephw** [comment]
Thank you!

**Pull request closed without merging**
