### PR TITLE
[MCHECKSTYLE-272]  Update checkstyle plugin for checkstyle-6.2

### PR DESCRIPTION
**Pull request by hgschmie**
After applying the change to trunk, the changes to the integration test poms (which load resources from the MCHECKSTYLE-272 branch) are no longer necessary.

### CODE REVIEW

**Comment by dennisl** [comment]
The relevant parts of this pull request has been merged to the canonical svn repo.

**Comment by dennisl** [comment]
I don't seem to have permissions to close this pull request. Can someone please close it?

**Comment by michael-o** [comment]
@hgschmie Please close this SR.

**Comment by michael-o** [comment]
@hgschmie Please close.

**Pull request closed without merging**
