### PR TITLE
MPIR-268: Mirror Dependency Information to Maven Central

### PR DESCRIPTION
**Pull request by hazendaz**
Add 'Gradle' to Grails as they are the same matching maven central.
Move SBT up in order and add 'Scala' to match maven central.

### CODE REVIEW

**Comment by hazendaz** [comment]
Any status on this PR?

**Comment by hazendaz** [comment]
Any status on this PR?

**Comment by michael-o** [comment]
You should have linked to the JIRA issue: https://issues.apache.org/jira/browse/MPIR-268. Request to reopen the issue, squash your commit and bring it uptodate with current trunk. I will review and pull in.

Next time please open an issue and then the PR otherwise we simply miss that.

**Comment by hazendaz** [comment]
@michael-o I have marked the commit with jira ticket number as well as PR.  I requested reopen and squashed commits as you asked.  Thanks for checking in on this.

**Comment by michael-o** [comment]
Running ITs...

**Comment by michael-o** [comment]
Damn, can't run any of the tests at work because the test mojo executor ignores my `settings.xml`. Have to rerun when I get back to my home machine.

**Comment by michael-o** [comment]
Cannot cleanly apply your patch:

```
[INFO] There are 10 errors reported by Checkstyle 6.1.1 with config/maven_checks.xml ruleset.
[ERROR] src/main/java/org/apache/maven/report/projectinfo/DependencyInformationReport.java[168] (sizes) LineLength: Zeile länger als 120 Zeichen
[INFO] Ignored 9 errors, 1 violation remaining.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 44.638 s (Wall Clock)
[INFO] Finished at: 2015-10-01T13:10:26+02:00
[INFO] Final Memory: 34M/407M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.15:check (checkstyle-check) on project maven-project-info-reports-plugin: You have 1 Checkstyle violation. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
```

The line is too long.

**Comment by hazendaz** [comment]
I'll look at this later tonight.

Sent by Outlook for Android

On Thu, Oct 1, 2015 at 4:13 AM -0700, "Michael Osipov" notifications@github.com wrote:
Cannot cleanly apply your patch:

```
[INFO] There are 10 errors reported by Checkstyle 6.1.1 with config/maven_checks.xml ruleset.
[ERROR] src/main/java/org/apache/maven/report/projectinfo/DependencyInformationReport.java[168] (sizes) LineLength: Zeile länger als 120 Zeichen
[INFO] Ignored 9 errors, 1 violation remaining.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 44.638 s (Wall Clock)
[INFO] Finished at: 2015-10-01T13:10:26+02:00
[INFO] Final Memory: 34M/407M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.15:check (checkstyle-check) on project maven-project-info-reports-plugin: You have 1 Checkstyle violation. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
```

The line is too long.

---

**Comment by hazendaz** [comment]
@michael-o Should be good now.  I ran a test build locally and it passes.

**Comment by hazendaz** [comment]
I just rebased.

**Comment by michael-o** [comment]
Thanks, will check next week.

**Comment by michael-o** [comment]
Patch is in test...

**Comment by hazendaz** [comment]
Thanks

Sent by Outlook for Android

On Tue, Oct 6, 2015 at 1:30 AM -0700, "Michael Osipov" notifications@github.com wrote:
Patch is in test...

---

**Comment by michael-o** [comment]
Where you able to run `mvn clean verify -Prun-its -Dinvoker.mergeUserSettings` and `mvn -Preporting site`? I receive:

```
[INFO] Generating "Invoker Build Results" report --- maven-invoker-plugin:1.9:report
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10:02 min
[INFO] Finished at: 2015-10-06T19:03:25+02:00
[INFO] Final Memory: 58M/191M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.4:site (default-site) on project maven-project-info-reports-plugin: Error generating maven-invoker-plugin:1.9:report: Failed to read report file: D:\Projekte\maven-project-info-reports-plugin\target\invoker-reports\invoker-summary.txt: input contained no data -> [Help 1]
```

The invoker summary is not written. I will try the latest tag first.

**Comment by michael-o** [comment]
I think, I have found the problem. This comes from a newly introduced changed in Plugins Parent 28-SNAPSHOT.

**Comment by michael-o** [comment]
Patch applied. Please close this PR. In future, please avoid adding unrelated changes like in `.gitignore` in _one_ PR.

**Comment by hazendaz** [comment]
Thanks @michael-o I thought to remove that as well.  I had it originally as a separate commit but squashed when asked to perform rebase / squash.  Anyway, I see it's not included and probably not worth the effort to include the ignore file.  Anyway, thanks for picking this PR up.  I'm closing the request as noted.

**Pull request closed without merging**
