### PR TITLE
Suggest using verify phase for Checkstyle

### PR DESCRIPTION
**Pull request by gaul**
The Maven lifecycle[1] reference suggests using validate to:

> validate the project is correct and all necessary information is available.

and verify to:

> run any checks to verify the package is valid and meets quality criteria.

The latter better matches Checkstyle's functionality and matches
similar tools like FindBugs[2].

[1] https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Lifecycle_Reference
[2] http://gleclaire.github.io/findbugs-maven-plugin/check-mojo.html

### CODE REVIEW

**Comment by sverhagen** [comment]
Isn't this going to stump many users that are by now used to seeing this happen in `validate`? Personally I've configured it to execute in or around the `verify` goal, and I've many times committed with Checkstyle errors because in the particular project I was so used only running `tomcat7:run` (which runs up to `compile` prior to running Tomcat). So I could see users wanting it to be run in `validate`. It now running in `validate` may arguable be _wrongish_, but it's defensible in my mind. Perhaps not worth breaking existing configurations over, particularly if you can already configure it to work the way you want it to work.

**Comment by gaul** [comment]
@sverhagen I hope most users do not use the validate phase for Checkstyle -- I have accidentally done so before and compilation errors cause confusing Checkstyle errors.  Instead they should use something at or after test-compile.  The verify phase seems most appropriate for this.

**Comment by dkulp** [comment]
I disagree with this change.   All the projects I use properly keep this in validate to make sure the SOURCE is correct prior to compilation.   A "mvn test" would not hit verify and since "mvn test" is generally what is recommended for developers prior to pushing changes, the chances of pushing improper code is way way higher.   The verify phase is to verify the PACKAGE, not the source.   

In addition, the other MAVEN provided plugins for this such as PMD also run in validate.

**Comment by khmarbaise** [comment]
I aggree with Daniel....it does not make sense to compile and test code which does not follow the required checkstyle rules...

**Comment by gaul** [comment]
Compare the output with checkstyle in the verify phase with the validate phase:

```
/home/gaul/work/s3proxy/src/main/java/org/gaul/s3proxy/S3Proxy.java:47: error: ';' expected
    sta tic {
           ^
1 error
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project s3proxy: Compilation failure -> [Help 1]
```

```
[WARNING] src/main/java/org/gaul/s3proxy/S3Proxy.java[47:5] (coding) DeclarationOrder: Variable access definition in wrong order.
[WARNING] src/main/java/org/gaul/s3proxy/S3Proxy.java[47:9] (design) VisibilityModifier: Variable 'tic' must be private and have accessor methods.
```

This is just the first example off the top of my head; I have tried using Checkstyle with the recommended validate phase and it emits much more confusing errors than in the verify phase.

**Comment by sverhagen** [comment]
I don't care much for either phase, I was just looking out for compatibility of people's builds. But since there seems to be appreciation for either solution, I see that as confirmation that this should only be changed with the greatest care, as to not break people's expectations. That's all.

**Comment by gaul** [comment]
Note that this commit merely changes the documentation; maven-checkstyle-plugin does not bind to any phase by default.

**Comment by sverhagen** [comment]
I totally misunderstood that. Then I withdraw all my objections. Perhaps the documentation could though acknowledge the two camps and explaining both use cases.

**Comment by dkulp** [comment]
How about something like:  

  Note that the phase that <<checkstyle::check>> is bound to is very important.  If bound to the validate phase, it would check the code prior to compiling the code.  If the code is invalid, the parsing errors reported by checkstyle may be different than what would be expected from the javac compiler.  However, it's guaranteed to run.   Another popular option is to bind it to the verify phase which would run much later (and allow the javac compiler to flag invalid code prior to checkstyle).   However, if developers generally just use "mvn test" prior to pushing changes, checkstyle would not run as verify occurs after the test phase.

prior to the example?

**Comment by sverhagen** [comment]
:+1:

**Pull request closed without merging**
