### PR TITLE
[MPMD-191] Update to PMD 5.2.1

### PR DESCRIPTION
**Pull request by adangel**
Changes in PMD:
- http://pmd.sourceforge.net/pmd-5.2.1/overview/changelog.html
- http://pmd.sourceforge.net/pmd-5.2.0/overview/changelog.html
- http://pmd.sourceforge.net/pmd-5.1.3/changelog.html

### CODE REVIEW

**Comment by olamy** [comment]
I believe @mfriedenhagen did the job? Maybe we can close this pr?

**Comment by mfriedenhagen** [comment]
Hello @olamy, yes I just called for a vote and the issue is already marked
as closed in JIRA :-)

**Comment by olamy** [comment]
so we have to ask @adangel to close this pr :-)

**Comment by adangel** [comment]
This is integrated (see http://jira.codehaus.org/browse/MPMD-191). Thanks!

**Pull request closed without merging**
