### PR TITLE
MSHADE-168: fix manifestEntries generic type

### PR DESCRIPTION
**Pull request by mcculls**
See http://jira.codehaus.org/browse/MSHADE-168 for background

### CODE REVIEW

**Comment by gaul** [comment]
:+1:

**Comment by mcculls** [comment]
Closing as this has been fixed independently by https://issues.apache.org/jira/browse/MSHADE-183

**Comment by regi4life** [comment]
Hello,

I am new in Maven. Please, how to execute this patch ?

Thank you.

Regi4life

**Comment by khmarbaise** [comment]
Use maven-shade-plugin version 2.4 and above...

**Comment by regi4life** [comment]
**It is in my basis pom.xml that i have to define the plugin maven-shade-plugin ?

Step by step how to proceed. I have the patch below but i do not know how to integrate it*\* :

_diff --git a/maven-shade-plugin/src/main/java/org/apache/maven/plugins/shade/resource/ManifestResourceTransformer.java b/maven-shade-plugin/src/main/java/org/apache/maven/plugins/shade/resource/ManifestResourceTransformer.java
index 644fad6..74bf3b7 100644
--- a/maven-shade-plugin/src/main/java/org/apache/maven/plugins/shade/resource/ManifestResourceTransformer.java
+++ b/maven-shade-plugin/src/main/java/org/apache/maven/plugins/shade/resource/ManifestResourceTransformer.java
@@ -47,7 +47,7 @@ public class ManifestResourceTransformer
     // Configuration
     private String mainClass;
-    private Map<String, Attributes> manifestEntries;
-    private Map<String, String> manifestEntries;
  
   // Fields
   private boolean manifestDiscovered;
  @@ -101,7 +101,7 @@ public class ManifestResourceTransformer
  
  ```
   if ( manifestEntries != null )
   {
  ```
-            for ( Map.Entry<String, Attributes> entry : manifestEntries.entrySet() )
-            for ( Map.Entry<String, String> entry : manifestEntries.entrySet() )
           {
               attributes.put( new Attributes.Name( entry.getKey() ), entry.getValue() );
           }_

**Pull request closed without merging**
