### PR TITLE
MPMD-197: PMD Plugin Updates

### PR DESCRIPTION
**Pull request by hazendaz**
Now that pmd plugin requires java 6, add types to lists and @Override annotations.  Additionally update some of the dependencies used by this module to more recent versions where code changes were not necessary.

### CODE REVIEW

**Comment by michael-o** [comment]
Can you kindly update this PR to reflect changes from trunk and open a JIRA issue for that. I will then merge this PR happily.

**Comment by hazendaz** [comment]
I have made one additional commit with more trivial items.  I created a Jira ticket for this and then added reference in the description here.  If you need me to rework this in anyway I will be more than happy to do so.  Thanks.

**Comment by hazendaz** [comment]
I have also rebased against latest codebase as of the last half hour.

**Comment by michael-o** [comment]
Patches merged with pleasure, please close this PR.

**Comment by hazendaz** [comment]
Rebased and verified coded was merged.  Thank you.  Closing out PR.

**Pull request closed without merging**
