### PR TITLE
Update error-prone integration test

### PR DESCRIPTION
**Pull request by cushon**
EmptyIf is no longer one of the default errors, use DeadException
instead.

### CODE REVIEW

**Comment by olamy** [comment]
OK thanks!!
Maybe update the home page http://errorprone.info/ 
:-)

**Comment by cushon** [comment]
Good call, home page is fixed now. Thanks!

**Comment by olamy** [comment]
merged, you can now close this pr.
Thanks!!

**Comment by cushon** [comment]
:thumbsup:

**Pull request closed without merging**
