### PR TITLE
Upgrade to Plexus Archiver 3.5-SNAPSHOT

### PR DESCRIPTION
**Pull request by snicoll**
See MASSEMBLY-854

Please note that this new release of plexus archiver requires Java7

### CODE REVIEW

**Comment by michael-o** [comment]
Rejecting PR. You mixing several things at once:

1. Upgrade to Java 7; this requires a seperate JIRA issue
2. We do not you use SNAPSHOTs in our components
3. Plexus IO upgrade needs s seperate ticket

**Comment by snicoll** [comment]
@michael-o I don't think I do: the Java7 upgrade is required by the upgrade of Plexus Archiver. The same apply for the plexus IO upgrade. In other words, those are side effects of upgrading to the upcoming plexus archiver 3.5

> We do you use SNAPSHOTs in our components

I'd like an official CI SNAPSHOT build of the maven assembly plugin so that we can ensure the issue on our side is fixed. But I've built the plugin locally so feel free to close this PR if it doesn't provide any added value.

**Comment by michael-o** [comment]
Let's clarify first: you PR does add value, but not in the way it is structured. The upgrade to Java 7 needs to be on the release notes list for users to clearly see that this plugin now requires Java 7 and not just Plexus Archiver was upgraded. Most people won't check transitive release notes.

The second point is a typo, *not* was missing. I believe you that the issue is now fixed, but point is that we do not use snapshots is that the entire build should rely on Maven Central only. Consider that people are locked down and are surprised that the dependency is not available. Moreover, there is no guarantee that the required snapshot exists on Apache Snapshots Nexus instance.

Just split up in several issues and I'd be happy to merge it.

**Comment by snicoll** [comment]
Closing in favour of #116 and #117

**Pull request closed without merging**
