### PR TITLE
[MSITE-654] Removed the slash

### PR DESCRIPTION
**Pull request by rajivpjs**
This is my first Apache source code change and I my ICLA agreement has been filed.

Could you please review this change in relation to MSITE-654? Please let me know whether I have missed anything.

Thanks.

### CODE REVIEW

**Comment by michael-o** [comment]
@rajivpjs Merged, please close.

**Comment by rajivpjs** [comment]
@michael-o - Thanks. That's great. My first source code change has been merged!!!.

What do I need to close?

**Comment by michael-o** [comment]
@rajivpjs No need anymore. The close was already done -- though several hours later.

**Comment by rajivpjs** [comment]
Ok. Thanks for letting me know.

Take care.

**Pull request closed without merging**
