### PR TITLE
[MSITE-705] Wagon logs displayed only if debug mode activated

### PR DESCRIPTION
**Pull request by axel3rd**
[MSITE-705](https://issues.apache.org/jira/browse/MSITE-705) : William Kemper patch + IT inclusion

### CODE REVIEW

**Comment by Tunaki** [comment]
Is it really needed to deploy to a mock FTP server for the test? The `Session: Disconnected` logs, even when not in debug mode, can be reproduced with a simple push to a local file based repository. I can update the PR with this.

**Comment by axel3rd** [comment]
@Tunaki : It is to be closest to the original issue (even if this is not SFTP, a little bit more complex to mock). The FTP/SFTP logs are different => I try to found a common pattern for assert. But I agree, a push on local file is more simple & sustainable. I can change or provide a new PR ASAP based on this use case if considered as recevable for patch inclusion.

**Comment by Tunaki** [comment]
I went ahead and updated the PR, will push this. Thanks!

**Comment by axel3rd** [comment]
OK, many thanks.

**Pull request closed without merging**
