### PR TITLE
MPDF-81 merging in the needed doxia modules required for copyright ov…

### PR DESCRIPTION
**Pull request by spyhunter99**
…errides, Add property based overrides for the copyright headers. Most of the real changes were in FoAggregatedSink

### CODE REVIEW

**Comment by hboutemy** [comment]
thanks for your efforts to transform your git repo to this PR

merging the Doxia modules sources in maven-pdf-plugin sources is not an option: we won't maintain 2 copy/pasted code bases
does it mean that you need some new API in Doxia (Sitetools) for the pdf plugin to use?
with the copy, I can't really understand what was changed.
if you need Doxia (Sitetools) update before being able to use them in pdf plugin, you'll need another pull request in Doxia (or Doxia Sitetools) source: https://github.com/apache/maven-doxia/ or https://github.com/apache/maven-doxia-sitetools/

and in pdf plugin source, please avoid unnecessary changes that hide the real useful ones

**Comment by spyhunter99** [comment]
unfortunately, the doxia crew does not ever set the maven the version to snapshots. Regardless, i tried to get the changes made to doxia directly, https://issues.apache.org/jira/browse/DOXIA-555

**Comment by spyhunter99** [comment]
and i don't blame you for being against this, i've unfortunately had to reject contributions for asf repos i own too for similar reasons

**Comment by hboutemy** [comment]
ok, I'll answer on DOXIA-555

**Pull request closed without merging**
