### PR TITLE
Correct jira.codehaus.org to issues.apache.org/jira

### PR DESCRIPTION
**Pull request by nhojpatrick**
Looking though several plugins (http://maven.apache.org/plugins/maven-install-plugin/issue-tracking.html) and discovered the currently published url for issue tracking is pointing to codehaus.

This pull requests corrects all the links to they point to valid end points.

### CODE REVIEW

**Comment by michael-o** [comment]
Looking into this PR right now.

**Comment by michael-o** [comment]
This patch is not complete. If I search for `jira.codehaus` I still have hits in a few test cases, XMLs and `invoker.properties`.

**Comment by nhojpatrick** [comment]
fixing those, but broke a test

can i use hamcrest when doing asserts??? e.g. assertThat( actual, containsString( expected) ); maven-doap-plugin is using assertTrue so unhelpful error messages about what was expected.

**Comment by michael-o** [comment]
@nhojpatrick Just fix what is most possible and I will have another look. Which tests exactly are failing?

**Comment by nhojpatrick** [comment]
@michael-o org.apache.maven.plugin.doap.DoapMojoTest#testGeneratedDoapArtifact currently slowly working though them but not easy just using assertTrue

**Comment by nhojpatrick** [comment]
Changed more jira.codehaus.org, all test passing, several codehaus links I couldn't find a working link at apache so didn't change it. Also a few tests appear to pick up codehaus from groupId or artifact so i didn't change those.

All codehaus jira links should now be pointing to the correct apache jira.

**Comment by michael-o** [comment]
Checking your patch right now...

**Pull request closed without merging**
