### PR TITLE
MJAVADOC-431 allow maven descriptor to javadoc jar

### PR DESCRIPTION
**Pull request by peterlynch**
replaces #57

### CODE REVIEW

**Comment by michael-o** [comment]
Looks better now but you or your IDE have shredded the formatting in existing code. Please restore and check newly created files for proper formatting.

**Comment by peterlynch** [comment]
@michael-o maybe I am misunderstanding your requirements.

For any file that I have touched, new or existing, I have formatted the entire file to match Maven code style.

Please be precise about what you need me to do. 

My latest guess about what you need is that for files that already existed, only format the new code I have added, but leave the rest of the file formatting alone? Is this it?

This feels like a lot of churn for not much benefit. Keep in mind the rest of the entire plugin has badly formatted code....

**Comment by michael-o** [comment]
As an example, please have a look at the diff of `JavadocJar.java`. You have deleted line 299 but changed formatting for numerous other lines. Same applies for the test class. The other Java files don't respect the formatting. Please see the [style](https://maven.apache.org/developers/conventions/code.html). The patch itself is perfectly fine and will be merged after those nits have been resolved.

**Comment by peterlynch** [comment]
@michael-o so...here is my current understanding of your needs...
- for files that already existed, leave the code style completely as it was before the patch, except for any new lines I add, make those new lines adhere to [style](https://maven.apache.org/developers/conventions/code.html).
- for completely new files, make sure the entire file is formatted according to [style](https://maven.apache.org/developers/conventions/code.html)

Is this accurate?

**Comment by michael-o** [comment]
Exactly!

**Comment by peterlynch** [comment]
part of my problem is the Maven idea codestyle file downloadable from the Maven site does not import properly to match the described preferences on the style page.

After some manual tweaking, I redid this pull hopefully for the last time. Checkstyle was happy at least...

see #73

**Comment by michael-o** [comment]
If something is wrong with the IDEA style file, please correct it and create an issue with MNGSITE.

**Pull request closed without merging**
