### PR TITLE
MCHANGES-373

### PR DESCRIPTION
**Pull request by mpet**

### CODE REVIEW

**Comment by mpet** [comment]
Can anyone help me to review and merge this?

**Comment by michael-o** [comment]
Why is the diff so huge?

**Comment by michael-o** [comment]
@mpet Why is the diff so huge?

**Comment by britter** [comment]
Probably whitespace / line break changes? Please reduce the change set so that only lines that have actually changed are included.

**Comment by mpet** [comment]
How do I make sure that I get the correct formatting?
'mvn clean process-sources'

//mikael

**Comment by britter** [comment]
@mpet this has nothing to do with maven. I'm pretty sure it's about line endings. You check whether your configuration is correct (see https://help.github.com/articles/dealing-with-line-endings/). Before committing you should call `git diff` to see whether only the lines you actually changed are marked as changed or all lines in a file. If the latter is the case, git has probably converted all line endings.

HTH
Benedikt

**Comment by mpet** [comment]
Hi,

I made the fix with line endings and now got just the lines that where changed. However it seems that I accidently pushed to trunk.

https://github.com/mpet/maven-plugins/commit/46df011b2c0c3aada2691409e1a7f3980232516a

What is the process to update my pull request? And how can I revert the commit?

**Comment by michael-o** [comment]
Reset local master to apache master, reapply the patch to your branch and force push it.

**Comment by mpet** [comment]
Hi,

git fetch origin
git reset --hard origin/trunk

Then I still have this on local trunk ( top line is my commit).

//mikael

$ git log
commit 46df011b2c0c3aada2691409e1a7f3980232516a
Author: mikael petterson mikaelpetterson@hotmail.com
Date:   Mon Sep 12 09:26:29 2016 +0200

```
Fixed line endings
```

commit 27a65d961624f4986a4c5a0b5ce34da9d7bdff23
Author: Karl Heinz Marbaise khmarbaise@apache.org
Date:   Mon Aug 22 19:24:37 2016 +0000

```
[maven-release-plugin] prepare for next development iteration

git-svn-id: https://svn.apache.org/repos/asf/maven/plugins/trunk@1757254 13f79535-47bb-0310-9956-ffa450edef68
```

commit db811162ce8f753460931747ec0b361577b0b946
Author: Karl Heinz Marbaise khmarbaise@apache.org
Date:   Mon Aug 22 19:24:07 2016 +0000

```
[maven-release-plugin] prepare release maven-war-plugin-3.0.0

git-svn-id: https://svn.apache.org/repos/asf/maven/plugins/trunk@1757252 13f79535-47bb-0310-9956-ffa450edef68
```

**Pull request closed without merging**
